# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BanCheck.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'BanCheck.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x42\x61nCheck.proto\x12\x08\x66reefire\"6\n\x0b\x42\x61nCheckReq\x12\x11\n\tAccountId\x18\x01 \x01(\x04\x12\x14\n\x0cNeedBanCheck\x18\x04 \x01(\x08\"8\n\x0b\x42\x61nCheckRes\x12)\n\tBasicInfo\x18\x01 \x01(\x0b\x32\x16.freefire.AccountBasic\"\x85\x01\n\x0c\x41\x63\x63ountBasic\x12\x11\n\tAccountId\x18\x01 \x01(\x04\x12\x10\n\x08Nickname\x18\x03 \x01(\t\x12\x0e\n\x06Region\x18\x05 \x01(\t\x12\r\n\x05Level\x18\x06 \x01(\r\x12\r\n\x05Likes\x18\x15 \x01(\r\x12\"\n\x07\x42\x61nInfo\x18Q \x01(\x0b\x32\x11.freefire.BanInfo\"C\n\x07\x42\x61nInfo\x12\x0f\n\x07\x42\x61nTime\x18\x04 \x01(\r\x12\x10\n\x08IsBanned\x18\x06 \x01(\x08\x12\x15\n\rRemainingTime\x18\x07 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BanCheck_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BANCHECKREQ']._serialized_start=28
  _globals['_BANCHECKREQ']._serialized_end=82
  _globals['_BANCHECKRES']._serialized_start=84
  _globals['_BANCHECKRES']._serialized_end=140
  _globals['_ACCOUNTBASIC']._serialized_start=143
  _globals['_ACCOUNTBASIC']._serialized_end=276
  _globals['_BANINFO']._serialized_start=278
  _globals['_BANINFO']._serialized_end=345
# @@protoc_insertion_point(module_scope)
